### ISSUE TITLE
Compatibility 0.97.0

### ISSUE THREAD

**Issue by rafdalb** [keatontaylor/alexa_media_player#274]
**Describe the bug**
After upgrade fron 0.96 to 0.97.0 (via hass.io) I get an log error and media players cannot be created: 

**To Reproduce**
0.96.x working
Upgrade to 0.97.0 log error and media players not appearing anymore.

Logs:
2019-08-08 16:15:12 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-08-08 16:15:20 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform alexa_media.media_player: Platform not found (cannot import name 'MEDIA_PLAYER_SCHEMA' from 'homeassistant.components.media_player' (/usr/src/homeassistant/homeassistant/components/media_player/__init__.py)).

**System details**
 - Home-assistant 0.97.0: 
 - Hassio (Yes/No): Yes, rebooted 4 times, same error, rebooting the full hw
 - alexa_media  (version from `const.py` or HA startup):
 - alexapy (version from `pip show alexapy` or HA startup):

this seems to be the issue: https://community.home-assistant.io/t/ha-0-97-update/130516/6

**Comment by rafdalb** [comment]
My fault, was using the old version, sorry.
